import SimpleGptExample from "~/components/simpleGpt";
import YoutubeScriptGPT from "~/components/ytScriptGpt";
import { type NextPage } from "next";
import Head from "next/head";
import CodeGPT from "~/components/codeGPT";


const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-8 flex items-center flex-col">
        <h1 className="text-4xl font-bold"> GPT Experiments</h1>
        <div className="flex w-screen flex-col p-8 space-y-8">
          <SimpleGptExample />
          <YoutubeScriptGPT />
          <CodeGPT />
          </div>
      </main>
    </>
  );
};

export default Home;
